apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3-provider
  labels:
    k8s-app: s3-provider
spec:
  selector:
    matchLabels:
      name: s3-provider
  template:
    metadata:
      labels:
        name: s3-provider
    spec:
      containers:
        - name: s3fuse
          image: ilhamfadhilah/s3-mounter
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                name: s3-credentials
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: mntdatas3fs
              mountPath: /var/s3fs:shared
      terminationGracePeriodSeconds: 30
      volumes:
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: mntdatas3fs
          hostPath:
            path: /mnt/s3data
